export const jobSkills = [
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "Go",
  "Ruby",
  "PHP",
  "HTML",
  "CSS",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Spring Boot",
  "ASP.NET",
  "SQL",
  "NoSQL",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "GraphQL",
  "REST APIs",
  "Next.js",
  "TypeScript",
  "Tailwind CSS",
  "Bootstrap",
  "jQuery",
  "SASS",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "CI/CD",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "AWS",
  "Azure",
  "Google Cloud",
  "Firebase",
  "Linux",
  "Unix",
  "Agile",
  "Scrum",
  "JIRA",
  "Figma",
  "UI/UX Design",
  "Wireframing",
  "Prototyping",
  "Responsive Design",
  "Testing",
  "Unit Testing",
  "Integration Testing",
  "Test Automation",
  "TDD",
  "Cybersecurity",
  "Penetration Testing",
  "Ethical Hacking",
  "DevOps",
  "Terraform",
  "Ansible",
  "Shell Scripting",
  "Bash",
  "PowerShell",
  "Data Structures",
  "Algorithms",
  "Data Analysis",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "Scikit-learn",
  "TensorFlow",
  "Keras",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Computer Vision",
  "AI",
  "Big Data",
  "Hadoop",
  "Spark",
  "ETL",
  "Data Warehousing",
  "Data Mining",
  "Business Intelligence",
  "Tableau",
  "Power BI",
  "Project Management",
  "Product Management",
  "Business Analysis",
  "Market Research",
  "Customer Success",
  "Digital Marketing",
  "SEO",
  "SEM",
  "Content Marketing",
  "Email Marketing",
  "Copywriting",
  "Branding",
  "Social Media",
  "Facebook Ads",
  "Google Ads",
  "CRM",
  "Salesforce",
  "HubSpot",
  "E-commerce",
  "Shopify",
  "WordPress",
  "Analytics",
  "Google Analytics",
  "Data Visualization",
  "Conversion Optimization",
  "Affiliate Marketing",
  "Accounting",
  "Bookkeeping",
  "Accounts Payable",
  "Accounts Receivable",
  "Payroll",
  "Budgeting",
  "Financial Analysis",
  "QuickBooks",
  "Excel",
  "Tax Preparation",
  "Audit",
  "Forecasting",
  "Financial Modeling",
  "Investment Analysis",
  "Risk Management",
  "Patient Care",
  "Medical Terminology",
  "CPR Certification",
  "EMR",
  "Epic Systems",
  "Vitals Monitoring",
  "Phlebotomy",
  "Nursing",
  "Medical Coding",
  "ICD-10",
  "Healthcare Administration",
  "HIPAA Compliance",
  "Medication Administration",
  "Teaching",
  "Lesson Planning",
  "Curriculum Development",
  "Classroom Management",
  "Educational Technology",
  "Instructional Design",
  "Online Teaching",
  "Special Education",
  "Tutoring",
  "Assessment",
  "Graphic Design",
  "Adobe Photoshop",
  "Illustrator",
  "InDesign",
  "After Effects",
  "Premiere Pro",
  "Canva",
  "3D Modeling",
  "Blender",
  "Animation",
  "Video Editing",
  "Photography",
  "UX Research",
  "Web Design",
  "Logo Design",
  "Plumbing",
  "Carpentry",
  "Electrical Work",
  "HVAC",
  "Welding",
  "Machining",
  "Blueprint Reading",
  "Forklift Operation",
  "Heavy Equipment Operation",
  "Construction",
  "Landscaping",
  "Painting",
  "Roofing",
  "Maintenance",
  "Auto Repair",
  "Communication",
  "Teamwork",
  "Leadership",
  "Time Management",
  "Critical Thinking",
  "Problem Solving",
  "Adaptability",
  "Creativity",
  "Collaboration",
  "Conflict Resolution",
  "Public Speaking",
  "Decision Making",
  "Work Ethic",
  "Interpersonal Skills",
  "Customer Service",
  "Empathy",
  "Negotiation",
  "Organization",
  "Attention to Detail",
  "Legal Research",
  "Legal Writing",
  "Paralegal",
  "Case Management",
  "Court Filings",
  "Compliance",
  "Contract Law",
  "Policy Analysis",
  "Grant Writing",
  "Public Policy",
  "Community Outreach",
  "Chemistry",
  "Biology",
  "Physics",
  "Mathematics",
  "Lab Skills",
  "CAD",
  "SolidWorks",
  "AutoCAD",
  "Mechanical Design",
  "Electrical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Technical Writing",
  "Interior Decorating",
  "AutoCAD Electrical",
  "Agile Methodology",
  "SCRUM Mastery",
  "Lean Management",
  "Kanban",
  "Six Sigma",
  "Kaizen",
  "Value Stream Mapping",
  "Root Cause Analysis",
  "Minitab",
  "Statistical Process Control",
  "Process Mapping",
  "Supply Chain Optimization",
  "Inventory Management",
  "Logistics Management",
  "Freight Coordination",
  "Procurement",
  "Purchasing",
  "Vendor Management",
  "Contract Negotiation",
  "Cost Reduction",
  "Material Handling",
  "Production Planning",
  "Capacity Planning",
  "Just-In-Time (JIT)",
  "ERP Systems",
  "SAP",
  "Oracle E-Business Suite",
  "Microsoft Dynamics",
  "Netsuite",
  "QuickBooks Online",
  "Sage 50",
  "Financial Reporting",
  "Cash Flow Management",
  "Treasury Management",
  "Bank Reconciliation",
  "GAAP",
  "IFRS",
  "Accounts Reconciliation",
  "ERP Implementation",
  "Fixed Asset Management",
  "Financial Statements",
  "Lease Accounting",
  "SOX Compliance",
  "Tax Compliance",
  "Payroll Taxes",
  "W-2/W-4 Processing",
  "1099 Filing",
  "Unemployment Claims",
  "Workers Compensation",
  "Human Resources",
  "Talent Acquisition",
  "Onboarding",
  "Offboarding",
  "HRIS",
  "BambooHR",
  "Workday",
  "ADP Workforce Now",
  "Benefits Administration",
  "Employee Relations",
  "Conflict Mediation",
  "Performance Reviews",
  "Compensation Planning",
  "Employee Training",
  "Learning Management Systems",
  "E-Learning Development",
  "LMS Administration",
  "Zoom",
  "Microsoft Teams",
  "Slack",
  "Notion",
  "Asana",
  "Trello",
  "Monday.com",
  "Basecamp",
  "Confluence",
  "ClickUp",
  "Airtable",
  "Zapier",
  "Make (Integromat)",
  "Data Entry",
  "Transcription",
  "Medical Transcription",
  "Legal Transcription",
  "Typing (100+ WPM)",
  "Proofreading",
  "Editing",
  "Copy Editing",
  "Technical Editing",
  "Fact Checking",
  "Translation",
  "Spanish Fluency",
  "French Fluency",
  "German Fluency",
  "Mandarin Fluency",
  "Arabic Fluency",
  "Japanese Fluency",
  "Portuguese Fluency",
  "Korean Fluency",
  "American Sign Language",
  "Simultaneous Interpretation",
  "Voiceover",
  "Podcast Editing",
  "Audio Mixing",
  "Music Production",
  "Sound Design",
  "GarageBand",
  "Pro Tools",
  "Ableton Live",
  "FL Studio",
  "Logic Pro",
  "Final Cut Pro",
  "DaVinci Resolve",
  "Camtasia",
  "OBS Studio",
  "ScreenFlow",
  "Live Streaming",
  "Twitch Streaming",
  "YouTube Content Creation",
  "TikTok Marketing",
  "Instagram Reels",
  "Influencer Outreach",
  "Community Management",
  "Brand Ambassador",
  "Social Media Management",
  "Content Scheduling",
  "Hashtag Strategy",
  "Social Listening",
  "Sentiment Analysis",
  "Content Repurposing",
  "Canva Pro",
  "Adobe Lightroom",
  "Photo Retouching",
  "Batch Editing",
  "Color Correction",
  "Event Photography",
  "Portrait Photography",
  "Product Photography",
  "Video Scripting",
  "Storyboarding",
  "Video Captions",
  "Closed Captioning",
  "Voice-to-Text",
  "Live Captioning",
  "eBook Formatting",
  "Kindle Direct Publishing",
  "Self-Publishing",
  "Book Marketing",
  "Manuscript Editing",
  "Academic Writing",
  "Thesis Formatting",
  "Research Analysis",
  "SPSS",
  "R Programming",
  "JMP Software",
  "SAS",
  "Quantitative Research",
  "Qualitative Research",
  "Survey Design",
  "Qualtrics",
  "Google Forms",
  "Market Segmentation",
  "Competitor Analysis",
  "A/B Testing",
  "Customer Surveys",
  "Focus Groups",
  "Customer Retention",
  "Customer Acquisition",
  "CRM Strategy",
  "Sales Pipeline Management",
  "Cold Calling",
  "Lead Generation",
  "B2B Sales",
  "B2C Sales",
  "Sales Forecasting",
  "Sales Reporting",
  "Account Management",
  "Client Onboarding",
  "Upselling",
  "Cross-Selling",
  "Customer Demos",
  "SaaS Sales",
  "CRM Cleanup",
  "Email Sequences",
  "Outbound Campaigns",
  "Inbound Strategy",
  "Call Center Management",
  "Zendesk",
  "Freshdesk",
  "Intercom",
  "HelpScout",
  "Technical Support",
  "Ticket Triage",
  "Live Chat Support",
  "IT Helpdesk",
  "Remote Troubleshooting",
  "VPN Configuration",
  "Network Security",
  "Firewall Setup",
  "Pen Testing",
  "SOC Monitoring",
  "Endpoint Security",
  "ISO 27001",
  "CIS Benchmarks",
  "NIST Compliance",
  "GDPR",
  "CCPA",
  "PCI DSS",
  "Security Awareness Training",
  "Incident Response",
  "Disaster Recovery",
  "Cloud Security",
  "Zero Trust Architecture",
  "Multi-Factor Authentication",
  "SSO Integration",
  "Okta",
  "Auth0",
  "API Security",
  "OAuth 2.0",
  "OpenID Connect",
  "Token Authentication",
  "JWT",
  "SSL/TLS",
  "HTTPS Implementation",
  "Load Balancing",
  "Nginx",
  "Apache",
  "HAProxy",
  "Reverse Proxy",
  "WebSockets",
  "Redis",
  "Memcached",
  "RabbitMQ",
  "Kafka",
  "Message Queues",
  "Event-Driven Architecture",
  "Microservices",
  "Monolithic Architecture",
  "Serverless",
  "AWS Lambda",
  "Azure Functions",
  "Google Cloud Functions",
  "Cloudflare",
  "CDN Management",
  "DNS Management",
  "Domain Configuration",
  "SSL Certificate Management",
  "Bash Scripting",
  "Zsh",
  "Command Line Tools",
  "Homebrew",
  "Systemd",
  "Cron Jobs",
  "Process Monitoring",
  "Log Analysis",
  "ELK Stack",
  "Prometheus",
  "Grafana",
  "Datadog",
  "New Relic",
  "Sentry",
  "Bug Tracking",
  "Error Logging",
  "App Performance Monitoring",
  "Code Review",
  "Pair Programming",
  "Agile Ceremonies",
  "Sprint Planning",
  "Daily Standups",
  "Sprint Retrospective",
  "Burndown Charts",
  "Velocity Tracking",
  "User Stories",
  "Acceptance Criteria",
  "Product Roadmapping",
  "Feature Prioritization",
  "Stakeholder Communication",
  "Technical Documentation",
  "Swagger",
  "Postman",
  "API Documentation",
  "API Testing",
  "Load Testing",
  "Stress Testing",
  "JMeter",
  "k6",
  "Unit Test Writing",
  "Jest",
  "Mocha",
  "Chai",
  "Cypress",
  "Playwright",
  "Selenium",
  "Enzyme",
  "Testing Library",
  "Code Coverage",
  "Mocking",
  "Stubbing",
  "CI/CD Pipelines",
  "GitHub Actions",
  "GitLab CI",
  "Bitbucket Pipelines",
  "CircleCI",
  "Travis CI",
  "Code Deployment",
  "Rollback Procedures",
  "Version Control",
  "Branching Strategy",
  "Git Rebase",
  "Git Merge",
  "Git Conflict Resolution",
  "Monorepo Management",
  "Nx",
  "Turborepo",
  "Lerna",
  "Package Management",
  "npm",
  "Yarn",
  "pnpm",
  "Dependency Management",
  "Semantic Versioning",
  "Code Linting",
  "ESLint",
  "Prettier",
  "Husky",
  "Lint Staged",
  "Commitlint",
  "Conventional Commits",
  "Changelog Generation",
  "Release Automation",
  "npm Publishing",
  "Scoped Packages",
  "Module Federation",
  "Webpack",
  "Vite",
  "Rollup",
  "Parcel",
  "Babel",
  "TypeScript Configuration",
  "tsconfig",
  "JSX",
  "TSX",
  "Functional Components",
  "React Hooks",
  "Custom Hooks",
  "Context API",
  "Redux",
  "Redux Toolkit",
  "Recoil",
  "Zustand",
  "React Query",
  "SWR",
  "MobX",
  "useEffect",
  "useState",
  "useMemo",
  "useCallback",
  "Memoization",
  "Lazy Loading",
  "Code Splitting",
  "Dynamic Imports",
  "Suspense",
  "Error Boundaries",
  "Next.js Routing",
  "App Router",
  "Pages Router",
  "Static Site Generation",
  "Server-Side Rendering",
  "Incremental Static Regeneration",
  "API Routes",
  "Middleware",
  "Custom Server",
  "getServerSideProps",
  "getStaticProps",
  "getInitialProps",
  "Deployment with Vercel",
  "Vercel Functions",
  "Netlify Deployment",
  "GitHub Pages",
  "Firebase Hosting",
  "S3 Static Site",
  "CloudFront Caching",
  "Meta Tags",
  "Open Graph",
  "Twitter Cards",
  "SEO Optimization",
  "Lighthouse Audits",
  "Accessibility Audits",
  "ARIA Roles",
  "Keyboard Navigation",
  "Screen Reader Testing",
  "Color Contrast Testing",
  "Responsive Layouts",
  "Flexbox",
  "CSS Grid",
  "Clamp Units",
  "Media Queries",
  "Mobile First Design",
  "Tailwind Utilities",
  "Component Libraries",
  "ShadCN",
  "Chakra UI",
  "Material UI",
  "Ant Design",
  "Headless UI",
  "Radix UI",
  "Storybook",
  "Component Testing",
  "Design Systems",
  "Tokens",
  "CSS Variables",
  "Dark Mode",
  "Theme Switching",
  "Internationalization (i18n)",
  "Localization (l10n)",
  "Next-i18next",
  "React Intl",
  "Date Formatting",
  "Currency Formatting",
  "Timezone Conversion",
  "Moment.js",
  "date-fns",
  "Luxon",
  "Time Picker",
  "Date Picker",
  "Multithreading",
  "Concurrency",
  "Parallel Computing",
  "Asynchronous Programming",
  "Event Loop",
  "Promises",
  "Async/Await",
  "Web Workers",
  "Message Passing",
  "Debouncing",
  "Throttling",
  "State Machines",
  "XState",
  "Finite State Machines",
  "Statecharts",
  "Design Patterns",
  "Factory Pattern",
  "Observer Pattern",
  "Singleton Pattern",
  "Strategy Pattern",
  "Builder Pattern",
  "Decorator Pattern",
  "Adapter Pattern",
  "Proxy Pattern",
  "Command Pattern",
  "MVC",
  "MVVM",
  "Flux",
  "Clean Architecture",
  "Hexagonal Architecture",
  "Domain-Driven Design",
  "Behavior-Driven Development",
  "Feature Flags",
  "A/B Testing",
  "Multivariate Testing",
  "User Testing",
  "Heatmaps",
  "Session Recording",
  "Conversion Funnel Analysis",
  "Google Tag Manager",
  "Segment",
  "Amplitude",
  "Mixpanel",
  "Heap Analytics",
  "Customer Journey Mapping",
  "Usability Testing",
  "Remote Testing",
  "Beta Testing",
  "Canary Releases",
  "Blue/Green Deployment",
  "Feature Toggles",
  "Dark Launches",
  "API Gateway",
  "Amazon API Gateway",
  "Kong",
  "Zuul",
  "Istio",
  "Service Mesh",
  "Sidecar Pattern",
  "gRPC",
  "Protocol Buffers",
  "Thrift",
  "OpenAPI",
  "Swagger Codegen",
  "AsyncAPI",
  "WebRTC",
  "Peer-to-Peer Communication",
  "Voice over IP",
  "Video Streaming",
  "HLS",
  "DASH",
  "Media Queries Level 4",
  "CSS Custom Properties",
  "Logical Properties",
  "Container Queries",
  "View Transitions API",
  "Intersection Observer",
  "Resize Observer",
  "Mutation Observer",
  "Scroll Events",
  "Sticky Elements",
  "CSS Backdrop Filter",
  "Glassmorphism",
  "Aspect-Ratio Utility",
  "3D Transforms",
  "Perspective",
  "Parallax Scrolling",
  "Framer Motion",
  "GSAP",
  "React Spring",
  "Three.js",
  "WebGL",
  "Canvas API",
  "SVG Animation",
  "Lottie",
  "Rive Animation",
  "Motion Design",
  "Accessibility Testing",
  "Axe-core",
  "Wave Tool",
  "Tab Order",
  "Alt Text",
  "Focus Management",
  "Skip Links",
  "Responsive Typography",
  "Fluid Typography",
  "Modular Scale",
  "Rem Units",
  "Em Units",
  "Relative Sizing",
  "Z-Index Management",
  "Stacking Context",
  "Positioning",
  "Absolute Positioning",
  "Fixed Positioning",
  "Sticky Positioning",
  "Static Positioning",
  "Component Lifecycle",
  "Mounting",
  "Unmounting",
  "Hydration",
  "Server Components",
  "Client Components",
  "Streaming",
  "Partial Rendering",
  "Server Actions",
  "Edge Functions",
  "Middleware Functions",
  "Database Optimization",
  "Indexing",
  "Normalization",
  "Denormalization",
  "Query Optimization",
  "Query Caching",
  "Write-Ahead Logging",
  "ACID Properties",
  "CAP Theorem",
  "BASE Properties",
  "Sharding",
  "Replication",
  "Failover",
  "Backup Strategies",
  "Disaster Recovery",
  "Security Patching",
  "Encryption at Rest",
  "Encryption in Transit",
  "HMAC",
  "Hashing",
  "Salting",
  "Brute Force Protection",
  "Rate Limiting",
  "IP Whitelisting",
  "Two-Factor Authentication",
  "Multi-Factor Authentication",
  "OAuth Scopes",
  "Token Expiry",
  "Session Storage",
  "Refresh Tokens",
  "Revocation",
  "Audit Logs",
  "Monitoring",
  "Logging Levels",
  "Structured Logging",
  "Log Rotation",
  "Distributed Tracing",
  "OpenTelemetry",
  "Jaeger",
  "Zipkin",
  "SAML",
  "SFTP",
  "FTP",
  "WebDAV",
  "File Uploads",
  "Chunked Uploads",
  "File Validation",
  "File Parsing",
  "CSV Parsing",
  "Excel Parsing",
  "PDF Generation",
  "PDF Parsing",
  "Docx Generation",
  "Text Extraction",
  "Optical Character Recognition",
  "Tesseract OCR",
  "Barcode Scanning",
  "QR Code Generation",
  "JWT Authentication",
  "API Token Management",
  "Admin Panels",
  "Role-Based Access Control",
  "Permission Systems",
  "User Onboarding",
  "Signup Flows",
  "Email Verification",
  "Password Reset",
  "Magic Links",
  "Social Login",
  "Single Sign-On",
  "Captcha",
  "reCAPTCHA v2",
  "reCAPTCHA v3",
  "hCaptcha",
  "Spam Prevention",
  "Email Deliverability",
  "SPF",
  "DKIM",
  "DMARC",
  "Email Templates",
  "Transactional Email",
  "Marketing Email",
  "Drip Campaigns",
  "Unsubscribe Management",
  "Webhooks",
  "Webhook Signature Verification",
  "Idempotency",
  "Retry Logic",
  "Circuit Breaker",
  "Rate Limiting Headers",
  "Retry-After Header",
  "Cash handling",
  "Food preparation",
  "Customer service",
  "Order taking",
  "POS system operation",
  "Fryer operation",
  "Grill cooking",
  "Line cook support",
  "Drive-thru operation",
  "Food safety",
  "Cleanliness and sanitation",
  "Stocking supplies",
  "Inventory rotation",
  "Dishwashing",
  "Multitasking",
  "Upselling",
  "Portion control",
  "Teamwork",
  "Time management",
  "Attention to detail",
  "Stocking shelves",
  "Bagging groceries",
  "Operating a cash register",
  "Barcode scanning",
  "Cleaning and organizing",
  "Customer greeting",
  "Labeling and pricing items",
  "Loss prevention awareness",
  "Handling returns/exchanges",
  "Shelf facing",
  "Inventory checks",
  "Store opening/closing",
  "Sweeping and mopping",
  "Trash removal",
  "Restroom sanitation",
  "Vacuuming",
  "Window cleaning",
  "Floor buffing",
  "Basic repair knowledge",
  "Use of cleaning chemicals",
  "Safety procedures",
  "Time efficiency",
  "Answering phones",
  "Data entry",
  "Scheduling",
  "Filing paperwork",
  "Basic computer skills",
  "Microsoft Word",
  "Microsoft Excel",
  "Typing",
  "Customer follow-up",
  "Listening skills",
  "Conflict resolution",
  "Package sorting",
  "Loading/unloading",
  "Picking and packing",
  "Pallet jack use",
  "Forklift",
  "Inventory tracking",
  "Shipping/receiving",
  "Basic labeling",
  "Safety protocol",
  "Order Picking",
  "Packing",
  "Shipping and Receiving",
  "Labeling",
  "Inventory Checks",
  "Forklift Operation",
  "Pallet Wrapping",
  "Lifting and Moving Boxes",
  "Barcode Scanning",
  "Load/Unload Trucks",
  "Team Safety",
  "Basic Maintenance"
]