export const softSkills = [
    "Adaptability",
    "Communication",
    "Problem Solving",
    "Time Management",
    "Teamwork",
    "Critical Thinking",
    "Conflict Resolution",
    "Creativity",
    "Attention",
    "Empathy",
    "Emotional Intelligence",
    "Listening",
    "Accountability",
    "Decision Making",
    "Flexibility",
    "Interpersonal Skills",
    "Leadership",
    "Motivation",
    "Work Ethic",
    "Resilience",
    "Patience",
    "Negotiation",
    "Organization",
    "Open-Mindedness",
    "Persuasion",
    "Positivity",
    "Stress Control",
    "Confidence",
    "Awareness",
    "Integrity",
    "Dependability",
    "Feedback",
    "Collaboration",
    "Initiative",
    "Resourcefulness",
    "Delegation",
    "Coaching",
    "Presentation",
    "Customer Service",
    "Relationships",
    "Respectfulness",
    "Adaptability",
    "Willingness",
    "Professionalism",
    "Discipline",
    "Curiosity",
    "Strategic Thinking",
    "Sound Judgment",
    "Tactfulness",
    "Agility",
    "Honesty",
    "Kindness",
    "Perseverance",
    "Competence",
    "Diplomacy",
    "Clarity",
    "Humility",
    "Grit",
    "Vision",
    "Self-Reflection",
    "Tolerance",
    "Understanding",
    "Team Support",
    "Innovation",
    "Recognition",
    "Criticism",
    "Nonverbal Skills",
    "Mediation",
    "Etiquette",
    "Reliability",
    "Networking",
    "Cross-Talking",
    "Transparency",
    "Inclusiveness",
    "Reading",
    "Empowerment",
    "Conflict Control",
    "Delegating",
    "Communication",
    "Enthusiasm",
    "Verbal Skills",
    "Tool Usage",
    "Fast Learning",
    "Goal Setting",
    "Productivity",
    "Detail Focus",
    "Calmness",
    "Systems Thinking",
    "Efficiency",
    "Judgment",
    "Writing",
    "Multitasking",
    "Data Literacy",
    "Tech Curiosity",
    "Awareness",
    "Growth Mindset",
    "Idea Sharing",
    "Supportive",
    "Prioritization",
    "Ambiguity",
    "Rapport",
    "Awareness",
    "Gratitude",
    "Motivation",
    "Mentoring",
    "Self-Motivation",
    "Virtual Etiquette",
    "Deadlines",
    "Proactivity",
    "Planning",
    "Expectations",
    "Focus",
    "Tenacity",
    "Authority",
    "Sensitivity",
    "Assertiveness",
    "Humor",
    "Volunteering",
    "Self-Care",
    "Trust",
    "Diversity",
    "Brainstorming",
    "Clarifying",
    "Initiative",
    "Cooperation",
    "Boundaries",
    "Management",
    "Resourcefulness",
    "Ethics",
    "Influence",
    "Challenging",
    "Punctuality",
    "Client Care",
    "Help-Seeking",
    "Solutions",
    "Gratitude",
    "Peer Support",
    "Politeness",
    "Anticipation",
    "Repetition",
    "Independence",
    "Mindset",
    "Consensus",
    "Planning",
    "Feedback",
    "Outcome Focus",
    "Civility",
    "Inclusivity",
    "Task Balancing",
    "Criticism",
    "Development",
    "Clarification",
    "Quality",
    "Onboarding",
    "Recognition",
    "Optimism",
    "Uncertainty",
    "Explaining",
    "Instructions",
    "Dialogue",
    "Clarity",
    "Adaptability",
    "Celebration",
    "Belonging",
    "Empathy",
    "Focus",
    "Support",
    "Openness",
    "Accountability",
    "Ownership",
    "Stress Control",
    "Self-Talk",
    "Mentoring",
    "Culture",
    "Confidence"
];